### PR TITLE
Proposal - lighter docker container

### PR DESCRIPTION
**Pull request by loranger**
Here is a proposal for a reusable docker container with a lighter footprint, and easier for mirotalk developments.

## Structure:

Instead of building a monolithic image embedding the app, this docker-compose file uses a custom node image (the latest official node image enhanced with gcc and pip).

`npm`: This image is built if not exists, has npm as entrypoint, mounts the whole project and can be used for dealing with dependencies.

`mirotalksfu`: The custom node image is re-used for launching the server.

## Pros:

It permits incremental updates without having to build a new image each time.
It allows to follow node releases for building custom node image with a minimal footprint and in a minimal building time.
It allows to develop locally from the mounted volume and serve the modifications directly from docker without having to build any image.

## Cons:

I can't find any disadvantage.
Maybe not being able to use CI for building and sharing pre-built images on docker hub ?

## Tips:

The npm container is named `npm` in order to simplify docker-compose usage :

```bash
$ docker-compose run npm update
$ docker-compose run --rm npm install mediasoup --save
$ docker-compose run npm outdated
```

## Motivations:

Finally, here is my before/after process in order to update my mirotalksfu. This is what motivates me to rewrite the docker-compose file

#### Before

```bash
$ git pull
$ docker-compose build
$ docker-compose up -d
```

#### After

```bash
$ git pull
```

### CODE REVIEW

**Comment by loranger** [comment]
Actually, my latest mirotalksfu update failed and I was not able to fix it, that's why I decied to switch to a portable node image.

<details>
<summary>log output</summary>

```bash
$ docker-compose build
Sending build context to Docker daemon  7.349MB
Step 1/14 : FROM ubuntu:20.04
 ---> 1a437e363abf
Step 2/14 : WORKDIR /src
 ---> Using cache
 ---> 127741a52ca9
Step 3/14 : RUN 	apt-get update && 	apt-get install -y build-essential
 ---> Using cache
 ---> 59764c3c6f9d
Step 4/14 : RUN 	DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && 	apt install -y software-properties-common && 	add-apt-repository ppa:deadsnakes/ppa && 	apt update && 	apt install -y python3.8 python3-pip
 ---> Using cache
 ---> 8d9164501485
Step 5/14 : RUN 	apt install -y curl dirmngr apt-transport-https lsb-release ca-certificates && 	curl -sL https://deb.nodesource.com/setup_16.x | bash - && 	apt-get install -y nodejs && 	npm install -g npm@latest
 ---> Running in c16e216b7f16

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
lsb-release is already the newest version (11.1.0ubuntu2).
lsb-release set to manually installed.
ca-certificates is already the newest version (20210119~20.04.2).
ca-certificates set to manually installed.
dirmngr is already the newest version (2.2.19-3ubuntu2.1).
dirmngr set to manually installed.
The following additional packages will be installed:
  libcurl4 libnghttp2-14 librtmp1 libssh-4
The following NEW packages will be installed:
  apt-transport-https curl libcurl4 libnghttp2-14 librtmp1 libssh-4
0 upgraded, 6 newly installed, 0 to remove and 1 not upgraded.
Need to get 704 kB of archives.
After this operation, 2146 kB of additional disk space will be used.
Err:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 apt-transport-https all 2.0.6
  404  Not Found [IP: 185.125.190.36 80]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libnghttp2-14 amd64 1.40.0-1build1 [78.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2build1 [54.9 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libssh-4 amd64 0.9.3-2ubuntu2.2 [170 kB]
Ign:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4 amd64 7.68.0-1ubuntu2.7
Ign:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 curl amd64 7.68.0-1ubuntu2.7
Err:5 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4 amd64 7.68.0-1ubuntu2.7
  404  Not Found [IP: 185.125.190.36 80]
Err:6 http://security.ubuntu.com/ubuntu focal-updates/main amd64 curl amd64 7.68.0-1ubuntu2.7
  404  Not Found [IP: 185.125.190.36 80]
Fetched 304 kB in 20s (14.8 kB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/a/apt/apt-transport-https_2.0.6_all.deb  404  Not Found [IP: 185.125.190.36 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.68.0-1ubuntu2.7_amd64.deb  404  Not Found [IP: 185.125.190.36 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.68.0-1ubuntu2.7_amd64.deb  404  Not Found [IP: 185.125.190.36 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
1 error occurred:
	* Status: The command '/bin/sh -c apt install -y curl dirmngr apt-transport-https lsb-release ca-certificates && 	curl -sL https://deb.nodesource.com/setup_16.x | bash - && 	apt-get install -y nodejs && 	npm install -g npm@latest' returned a non-zero code: 100, Code: 100

```

</details>

**Comment by miroslavpejic85** [comment]
> Actually, my latest mirotalksfu update failed and I was not able to fix it, that's why I decied to switch to a portable node image.
> 
> log output

Hey @loranger, 
MiroTalk has been tested with node 12x, 14x, 16x I'm not sure if it works with latest 18X. However to realign yourself with the latest changes, just this time delete the old image and recreate a new one and it should work. Usually if don't modify the package.json the docker-compose build should take a few seconds, you can run something like this script on your server:

```bash
cd mirotalksfu
git pull
docker-compose down
docker-compose build
docker images |grep '<none>' |awk '{print $3}' |xargs docker rmi
docker-compose up -d
```

Only the first time you install MiroTalk takes some time because it has to install mediasoup and all its dependencies, after the updates are almost instant if don't touch the package.json.

**Comment by loranger** [comment]
Hi Miroslav,

Thanks for your reply !

There was a clock issue on my local server (and AMD Ryzen 5 5600G running debian 10), which led to my `404  Not Found` on ubuntu apt servers inside docker containers.
This is now fixed and I finally managed to update my current mirotalksfu image (which was few commits behind) and I had to wait 7mn 30s for the image to build. 
Of course, it's a cache build issue, but that's not a convenient way to update a service, in my humble opinion.

Regarding the other applications I used to host using docker, it seems there are two approaches:
- The *bundle* release where the project is build in one image, pushed on a registry (hub.docker) and every consumer just have to docker pull in oder to get an updated service.
- The *dev* release where the project binaries are kepts untouched as docker services, the project source is mounted as a volume which can be easily modified and update with a simple pull from the main repository.

Mirotalksfu seems to use both approach and make it difficult to update because an automated update (such as watchtower or diun) can't be used and the manual one requires an extra step to pull, build and restart the application whereas a simple css file was changed.

Maybe a good solution would be to provide a pre-built image (using [github actions ?](https://github.com/marketplace/actions/build-and-push-docker-images)) on every update ?

Anyway, I rewrote the Dockerfile using the official `node:alpine` version and end up with a 445MB custom mirotalksfu-npm image which seems awesome to me. You could of course stick with a `node:16-alpine` but the latest version seems to work fine.

**Comment by miroslavpejic85** [comment]
Hi @loranger,
I agree with you, I tried your image on Ubuntu it works quite well, but on `macOs` (Monterey v12.4) it has some annoyances.
```bash
mirotalksfu    | node:internal/errors:466
mirotalksfu    |     ErrorCaptureStackTrace(err);
mirotalksfu    |     ^
mirotalksfu    | 
mirotalksfu    | Error: spawn Unknown system error -8
mirotalksfu    |     at ChildProcess.spawn (node:internal/child_process:413:11)
mirotalksfu    |     at spawn (node:child_process:689:9)
mirotalksfu    |     at new Worker (/src/node_modules/mediasoup/node/lib/Worker.js:76:49)
mirotalksfu    |     at Object.createWorker (/src/node_modules/mediasoup/node/lib/index.js:30:20)
mirotalksfu    |     at createWorkers (/src/app/src/Server.js:345:38)
mirotalksfu    |     at /src/app/src/Server.js:336:11
mirotalksfu    |     at Object.<anonymous> (/src/app/src/Server.js:337:3)
mirotalksfu    |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
mirotalksfu    |     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
mirotalksfu    |     at Module.load (node:internal/modules/cjs/loader:981:32) {
mirotalksfu    |   errno: -8,
mirotalksfu    |   code: 'Unknown system error -8',
mirotalksfu    |   syscall: 'spawn'
mirotalksfu    | }
mirotalksfu    | 
mirotalksfu    | Node.js v18.2.0
mirotalksfu    | npm notice 
mirotalksfu    | npm notice New minor version of npm available! 8.9.0 -> 8.12.1
mirotalksfu    | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.12.1>
mirotalksfu    | npm notice Run `npm install -g npm@8.12.1` to update!
mirotalksfu    | npm notice 
```
Are you able to test it also on macOs? 
Many thanks.

**Comment by loranger** [comment]
Hi Miroslav,

Actually, my debian server hosts released services. My dev server is dockerized projects running on my Macbook, and this mirotalksfu forked repository is one of them.

<details>
<summary>build and run log output</summary>

```bash
$ sw_vers
ProductName:    macOS
ProductVersion: 12.4
BuildVersion:   21F79

~/Developer/projects/mirotalksfu main
$ docker-compose build --no-cache
[+] Building 12.0s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 143B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/node:alpine             2.1s
 => [1/4] FROM docker.io/library/node:alpine@sha256:7ab82182ec72ea2042e29  3.2s
 => => resolve docker.io/library/node:alpine@sha256:7ab82182ec72ea2042e29  0.0s
 => => sha256:7ab82182ec72ea2042e29f40fd2d7badf3023302928 1.43kB / 1.43kB  0.0s
 => => sha256:955ef9fc772b94945b39072491472ad54afae845497 1.16kB / 1.16kB  0.0s
 => => sha256:3a3a4a29d79a2aa4399a3c10db017c21da44e3e08ea 6.69kB / 6.69kB  0.0s
 => => sha256:e841ba177aa3b6fe8b02024dff934422d6bad5f23 46.84MB / 46.84MB  1.5s
 => => sha256:92519577c68e2aa5e3d3ae6bda3448365d6c35f37d8 2.43MB / 2.43MB  0.4s
 => => sha256:27eab2450ab1f966ae39de575fcce58c79a55d5bcc048f6 450B / 450B  0.5s
 => => extracting sha256:e841ba177aa3b6fe8b02024dff934422d6bad5f2379eb718  1.5s
 => => extracting sha256:92519577c68e2aa5e3d3ae6bda3448365d6c35f37d84dbf6  0.1s
 => => extracting sha256:27eab2450ab1f966ae39de575fcce58c79a55d5bcc048f60  0.0s
 => [2/4] WORKDIR /src                                                     0.2s
 => [3/4] RUN apk add --update linux-headers alpine-sdk                    3.9s
 => [4/4] RUN apk add --update py-pip                                      2.0s
 => exporting to image                                                     0.6s
 => => exporting layers                                                    0.6s
 => => writing image sha256:8d616c6e02f4d371006dfd9a3a8615c9cd46eb08c9949  0.0s
 => => naming to docker.io/library/mirotalksfu-npm:latest                  0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

~/Developer/projects/mirotalksfu main 13s
$ docker-compose run --rm npm install

up to date, audited 186 packages in 628ms

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 8.11.0 -> 8.12.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.12.1
npm notice Run npm install -g npm@8.12.1 to update!
npm notice

~/Developer/projects/mirotalksfu main
$ docker-compose up
[+] Running 2/2
 ⠿ Container mirotalksfu-npm  Recreated                                    0.1s
 ⠿ Container mirotalksfu      Recreated                                    0.1s
Attaching to mirotalksfu, mirotalksfu-npm
mirotalksfu-npm  | 8.11.0
mirotalksfu-npm exited with code 0
mirotalksfu      |
mirotalksfu      | > mirotalksfu@1.0.0 start
mirotalksfu      | > node app/src/Server.js
mirotalksfu      |
mirotalksfu      | [2022-06-07 06:42:45.735] [Server] WORKERS: 5
mirotalksfu      | [2022-06-07 06:42:45.744] [Server]
mirotalksfu      |
mirotalksfu      |  ███████╗██╗ ██████╗ ███╗   ██╗      ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗
mirotalksfu      |  ██╔════╝██║██╔════╝ ████╗  ██║      ██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
mirotalksfu      |  ███████╗██║██║  ███╗██╔██╗ ██║█████╗███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
mirotalksfu      |  ╚════██║██║██║   ██║██║╚██╗██║╚════╝╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
mirotalksfu      |  ███████║██║╚██████╔╝██║ ╚████║      ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
mirotalksfu      |  ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝      ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝ started...
mirotalksfu      |
mirotalksfu      |
mirotalksfu      | [2022-06-07 06:42:45.744] [Server] Listening on {
mirotalksfu      |   node_version: '18.3.0',
mirotalksfu      |   hostConfig: {
mirotalksfu      |     protected: false,
mirotalksfu      |     username: 'username',
mirotalksfu      |     password: 'password',
mirotalksfu      |     authenticated: true
mirotalksfu      |   },
mirotalksfu      |   announced_ip: '127.0.0.1',
mirotalksfu      |   server: 'https://localhost:3010',
mirotalksfu      |   api_docs: 'https://localhost:3010/api/v1/docs',
mirotalksfu      |   mediasoup_server_version: '3.9.16',
mirotalksfu      |   mediasoup_client_version: '3.6.52',
mirotalksfu      |   sentry_enabled: false
mirotalksfu      | }
mirotalksfu      | [2022-06-07 06:43:13.076] [Server] Created room { room_id: '06298CleanPhoto' }
mirotalksfu      | [2022-06-07 06:43:13.090] [Server] User joined {
mirotalksfu      |   room_id: '06298CleanPhoto',
mirotalksfu      |   peer_info: {
mirotalksfu      |     detect_rtc_version: '1.4.1',
mirotalksfu      |     is_webrtc_supported: true,
mirotalksfu      |     is_mobile_device: false,
mirotalksfu      |     os_name: 'Mac OS X',
mirotalksfu      |     os_version: '10.15',
mirotalksfu      |     browser_name: 'Firefox',
mirotalksfu      |     browser_version: 103,
mirotalksfu      |     peer_id: 'hXoPvaGNgvibGft_AAAB',
mirotalksfu      |     peer_name: 'loranger',
mirotalksfu      |     peer_audio: true,
mirotalksfu      |     peer_video: true,
mirotalksfu      |     peer_screen: false,
mirotalksfu      |     peer_hand: false
mirotalksfu      |   },
mirotalksfu      |   peer_geo: null
mirotalksfu      | }
mirotalksfu      | [2022-06-07 06:43:13.097] [Server] Refresh Participants count { room_id: '06298CleanPhoto', peer_counts: 1 }
mirotalksfu      | [2022-06-07 06:43:13.106] [Server] Get RouterRtpCapabilities { peer_name: 'loranger' }
mirotalksfu      | [2022-06-07 06:43:13.145] [Server] Create webrtc transport { peer_name: 'loranger' }
mirotalksfu      | [2022-06-07 06:43:13.148] [Room] Adding transport { transportId: '53bfddb3-2979-48e2-9df2-e401276eeac5' }
mirotalksfu      | [2022-06-07 06:43:13.274] [Server] Create webrtc transport { peer_name: 'loranger' }
mirotalksfu      | [2022-06-07 06:43:13.276] [Room] Adding transport { transportId: '3b5e0fe1-9dfc-4e5b-a9fc-587e1a2e36f4' }
mirotalksfu      | [2022-06-07 06:43:13.280] [Server] Get producers { peer_name: 'loranger' }
mirotalksfu      | [2022-06-07 06:43:13.296] [Server] Connect transport { peer_name: 'loranger' }
mirotalksfu      | [2022-06-07 06:43:13.312] [Server] Produce {
mirotalksfu      |   kind: 'audio',
mirotalksfu      |   peer_name: 'loranger',
mirotalksfu      |   peer_id: 'hXoPvaGNgvibGft_AAAB',
mirotalksfu      |   producer_id: '608ae210-5ef0-4ee5-b694-18da2767094b'
mirotalksfu      | }
mirotalksfu      | [2022-06-07 06:43:13.334] [Server] Produce {
mirotalksfu      |   kind: 'video',
mirotalksfu      |   peer_name: 'loranger',
mirotalksfu      |   peer_id: 'hXoPvaGNgvibGft_AAAB',
mirotalksfu      |   producer_id: 'ce455489-07ed-413a-b4ab-485a85427028'
mirotalksfu      | }
mirotalksfu      | [2022-06-07 06:43:38.503] [Server] Disconnect { peer_name: 'loranger' }
mirotalksfu      | [2022-06-07 06:43:38.505] [Peer] Producer transport close {
mirotalksfu      |   peer_name: 'loranger',
mirotalksfu      |   consumer_id: '608ae210-5ef0-4ee5-b694-18da2767094b'
mirotalksfu      | }
mirotalksfu      | [2022-06-07 06:43:38.505] [Peer] Producer transport close {
mirotalksfu      |   peer_name: 'loranger',
mirotalksfu      |   consumer_id: 'ce455489-07ed-413a-b4ab-485a85427028'
mirotalksfu      | }
^CGracefully stopping... (press Ctrl+C again to force)
[+] Running 2/2
 ⠿ Container mirotalksfu-npm  Stopped                                      0.0s
 ⠿ Container mirotalksfu      Stopped                                      1.9s
canceled

~/Developer/projects/mirotalksfu main 1m 1s
$
```

</details>

Did you get this error on specific usage ?

**Comment by miroslavpejic85** [comment]
hi @loranger,

On startup.

<details>
<summary>build and run log output</summary>

```bash
miroslavpejic@MacBook-Pro-di-Miroslav ~/g/t/mirotalksfu (main)> sw_vers
ProductName:    macOS
ProductVersion: 12.4
BuildVersion:   21F79

miroslavpejic@MacBook-Pro-di-Miroslav ~/g/t/mirotalksfu (main)> docker --version
Docker version 20.10.16, build aa7e414

miroslavpejic@MacBook-Pro-di-Miroslav ~/g/t/mirotalksfu (main)> docker-compose build --no-cache
[+] Building 9.3s (8/8) FINISHED                                                                                                                       
 => [internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 143B                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:alpine                                                                                    1.2s
 => [1/4] FROM docker.io/library/node:alpine@sha256:7ab82182ec72ea2042e29f40fd2d7badf3023302928600803e2c158be85aee94                              0.0s
 => CACHED [2/4] WORKDIR /src                                                                                                                     0.0s
 => [3/4] RUN apk add --update linux-headers alpine-sdk                                                                                           4.8s
 => [4/4] RUN apk add --update py-pip                                                                                                             2.2s
 => exporting to image                                                                                                                            1.1s 
 => => exporting layers                                                                                                                           1.1s 
 => => writing image sha256:9aebfaf82d6461f057b6a9fe836b58cca4981e92f63f63683c257a79f2f67f4a                                                      0.0s 
 => => naming to docker.io/library/mirotalksfu-npm:latest                                                                                         0.0s 
miroslavpejic@MacBook-Pro-di-Miroslav ~/g/t/mirotalksfu (main)> docker-compose run --rm npm install
[+] Running 1/0                                                                                                                                        
 ⠿ Network mirotalksfu_default  Created                                                                                                           0.0s

up to date, audited 186 packages in 1s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.11.0 -> 8.12.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.12.1
npm notice Run npm install -g npm@8.12.1 to update!
npm notice 

miroslavpejic@MacBook-Pro-di-Miroslav ~/g/t/mirotalksfu (main)> docker-compose up
[+] Running 2/0
 ⠿ Container mirotalksfu      Created                                                                                                             0.1s
 ⠿ Container mirotalksfu-npm  Created                                                                                                             0.1s
Attaching to mirotalksfu, mirotalksfu-npm
mirotalksfu-npm  | 8.11.0
mirotalksfu-npm exited with code 0
mirotalksfu      | 
mirotalksfu      | > mirotalksfu@1.0.0 start
mirotalksfu      | > node app/src/Server.js
mirotalksfu      | 
mirotalksfu      | [2022-06-07 07:31:06.328] [Server] WORKERS: 6
mirotalksfu      | [2022-06-07 07:31:06.350] [Server] 
mirotalksfu      | 
mirotalksfu      |      ███████╗██╗ ██████╗ ███╗   ██╗      ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗ 
mirotalksfu      |      ██╔════╝██║██╔════╝ ████╗  ██║      ██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
mirotalksfu      |      ███████╗██║██║  ███╗██╔██╗ ██║█████╗███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
mirotalksfu      |      ╚════██║██║██║   ██║██║╚██╗██║╚════╝╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
mirotalksfu      |      ███████║██║╚██████╔╝██║ ╚████║      ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
mirotalksfu      |      ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝      ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝ started...
mirotalksfu      | 
mirotalksfu      | 
mirotalksfu      | [2022-06-07 07:31:06.350] [Server] Listening on {
mirotalksfu      |   node_version: '18.3.0',
mirotalksfu      |   hostConfig: {
mirotalksfu      |     protected: false,
mirotalksfu      |     username: 'username',
mirotalksfu      |     password: 'password',
mirotalksfu      |     authenticated: true
mirotalksfu      |   },
mirotalksfu      |   announced_ip: '127.0.0.1',
mirotalksfu      |   server: 'https://localhost:3010',
mirotalksfu      |   api_docs: 'https://localhost:3010/api/v1/docs',
mirotalksfu      |   mediasoup_server_version: '3.9.16',
mirotalksfu      |   mediasoup_client_version: '3.6.52',
mirotalksfu      |   sentry_enabled: false
mirotalksfu      | }
mirotalksfu      | [2022-06-07 07:31:06.354] [Server] Error: spawn Unknown system error -8
mirotalksfu      |     at ChildProcess.spawn (node:internal/child_process:413:11)
mirotalksfu      |     at spawn (node:child_process:689:9)
mirotalksfu      |     at new Worker (/src/node_modules/mediasoup/node/lib/Worker.js:76:49)
mirotalksfu      |     at Object.createWorker (/src/node_modules/mediasoup/node/lib/index.js:30:20)
mirotalksfu      |     at createWorkers (/src/app/src/Server.js:349:38)
mirotalksfu      |     at /src/app/src/Server.js:337:15
mirotalksfu      |     at Object.<anonymous> (/src/app/src/Server.js:341:3)
mirotalksfu      |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
mirotalksfu      |     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
mirotalksfu      |     at Module.load (node:internal/modules/cjs/loader:981:32) {
mirotalksfu      |   errno: -8,
mirotalksfu      |   code: 'Unknown system error -8',
mirotalksfu      |   syscall: 'spawn'
mirotalksfu      | }
```

</details>

**Comment by loranger** [comment]
Hi Miroslav,

I did test again, and tried with other node versions, but never had your error.
I used the following command in order to flush as data as I could 

```bash
docker-compose build --no-cache && rm -rf node_modules && docker-compose run --rm npm install --ddd && docker-compose up
```

I modified the pip dependency in order to use pip for python3 by default and it seems to build flawlesly, I ain't got any error, even with the log level set to *silly* (--ddd).

I also merged your latest modifications inside the repository in order to keep the pull request merge-able, but now I cannot test anymore 'cause I got a `Uncaught ReferenceError: tippy is not defined` error due to firefox blocking unpkg calls.

I will be out of town for the next few days but I will try to test this alpine version on different settings in order to reproduce your spawn error process

**Comment by miroslavpejic85** [comment]
Hi Loranger,

<details>
<summary>Steps to reproduce it</summary>

```bash
# Immagine someone want to try MiroTalk without docker
$ git clone https://github.com/miroslavpejic85/mirotalksfu.git
$ cd mirotalksfu
$ cp app/src/config.template.js app/src/config.js
$ cp docker-compose.template.yml docker-compose.yml
$ npm install # --> this cause the issue later when start it with Docker (it's create node_modules & package-lock.json)
$ npm start # all ok
# Then want to try it on Docker
$ docker-compose build --no-cache
$ docker-compose run --rm npm install 
$ docker-compose up
```
</details>

On startup you will get the error.

But don't worry about the spawn error, with
`rm -rf node_modules / package-lock.json` it resolve it.

My only concern about the alpine imgage is performance.

I tried it on my PC locally and it seems much slower than the ubuntu image.

As for the file `docker-compose`, the mount volume is fine, in this way every change is fired in real time or in some case need just to restart the app, not need to rebuild the image like before ;)

**Comment by loranger** [comment]
Hi Miroslav,

Sorry for the silence, I was away on business…

I'm surprised, alpine is supposed to be a smaller, lighter and faster os than the other distrib, and binaries are supposed to work as usual, regardless the distrib…

Maybe there is a dependency related issue for low level mediasoup libraries ? Or maybe a more [global issue with alpine](https://mediasoup.discourse.group/t/mediasoup-in-a-docker-image-running-alpine-latest-is-problematic/4302)

Anyway if you prefer and are more confortable with a debian/ubuntu based image, I tried again from a `node:slim` version and end up with a `574MB` image which is not bad. I did commit/pushed it (and ran lint too).

Please tell me what you do think of this version and if you notice some slowdowns.
I am on my side quite enthusiastic about the result.

**Comment by miroslavpejic85** [comment]
Hey Loranger,

don't worry, I'm also on holiday.

Regarding your docker-compose.yaml is ok for me ;)

How about keeping `ubuntu:20:04` on Dockerfile?

```Dockerfile
FROM ubuntu:20.04

WORKDIR /src

# gcc g++ make
RUN \
	apt-get update && \
	apt-get install -y build-essential

# Python 3.8 and pip
RUN \
	DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && \
	apt install -y software-properties-common && \
	add-apt-repository ppa:deadsnakes/ppa && \
	apt update && \
	apt install -y python3.8 python3-pip

# NodeJS 16.X and npm
RUN \
	apt install -y curl dirmngr apt-transport-https lsb-release ca-certificates && \
	curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
	apt-get install -y nodejs && \
	npm install -g npm@latest

# Vim editor
RUN apt-get install -y vim
```

The image will be slightly larger (659MB), but at least anyone can decide to install a different version of python, pip, NodeJS and so on, if mediasoup requirments changes in future, and on ubuntu 20.04 i'm sure it works very well.

Can you also test this last configuration? 
In my side seems ok.

Many thanks.

**Comment by loranger** [comment]
Lucky you !
I hope you enjoy

Regarding ubuntu, as you wish. 

The aim of the proposal was to provide a smaller docker container based on the latest official node image, without embedding the whole mirotalksfu project.

Your Dockerfile is working very fine, but I tried to reduce the size as much as I could.
With slim, you have a minimal debian where you can install essential dependencies, pip in any version and so on.
You could end up with the exact same result but for 403MB, with fewer lines, even with a node locked on version 16:

```dockerfile
FROM node:16-slim

WORKDIR /src
RUN \
    DEBIAN_FRONTEND=noninteractive apt update && \
    apt install -y --no-install-recommends build-essential python3-pip
```

Nothing forbids any future extra dependency installation, but if you are more confortable with ubuntu, just stick with it, you're the boss. On vacation, but still the boss ;)

**Comment by miroslavpejic85** [comment]
Hey @loranger,

Thank you for the boss :)

I like your last proposal, the image is much smaller.

```bash
mirotalksfu-npm   latest    07d45c4258be   27 minutes ago   437MB
```

For now I don't see any particular slowdowns on the performance as with Alpine image :)
Thanks for your great work

**Comment by miroslavpejic85** [comment]
Hi Loranger, 

In the end I did like this:

- I have mounted the two main folders of the app with docker-compose, so that all the changes made are reproduced in real time.

```yaml
        volumes:
            - ./app/:/src/app/:ro
            - ./public/:/src/public/:ro
```

- I created the image on Docker Hub which also includes the mediasoup modules which will always be updated to the latest version.

PROS: If there are no changes and updates to the app's dependencies to update it now just do 

```bash 
git pull
```


Otherwise, to make sure you are always up to date with both the app's dependencies and the code, just do this:

```bash
git pull
docker pull mirotalk/sfu:latest
docker-compose up -d
```

The times have improved considerably compared to before, as you do not have to build the image every time (like before), but it is already supplied ready with all the updates made by me upstream :)

What do you think?

Thank you.

**Comment by loranger** [comment]
I think that's awesome Miroslav !

Again I'm away, but I used the previous alpine image and even if I didn't have the opportunity to make a lot of video calls this month, it was working fine for the few tests I did.

I can't wait to use the official `mirotalk/sfu` image! As soon as I get back home, I'll try it and fix those conflicts in order to allow you to merge the PR, maybe.

**Comment by miroslavpejic85** [comment]
Thanks so much for your valuable feedback!

**Comment by loranger** [comment]
Hi Miroslav, I hope you're fine.

Sorry for the wait…
I did fix the conflicts and everything seems mergeable now.
Let me know if something is missing

**Comment by miroslavpejic85** [comment]
Hi Loranger,

It's nice to hear you again and Thank you so much, seems very good now! 

The image size is also reduced, from `803MB` to `574MB` and I test it on local seems also good, I don't see particular slowdowns like with alpine ;)

test

**Pull request merged**
