### PR TITLE
Support for Arm-based Docker images

### LINKED ISSUE #113: Support for Arm-based Docker images
Hi,
I found out that only amd64 docker image can be found on dockerhub.
I wonder if there is some plan or try about native support on arm architecture ?

### PR DESCRIPTION
**Pull request by rogerdz**
fix #113

### CODE REVIEW

**Comment by rogerdz** [comment]
Hi @miroslavpejic85, 

1. I'm not create Environment, I add the two variables in Secrets and variables -> Action 
image

2. Current it manual trigger in Action , so I added a commit so that the github workflow automatically runs when a new commit is pushed to the main branch
And yes, I tested github action workflow, The result is that the image will be only one as before mirotalk/sfu (your image is mirotalk/sfu:latest, not mirotalksfu/latest) but will also support linux/arm64, it will display in docker hub like this 
image

**Comment by miroslavpejic85** [comment]
Let's try :) Thank you for the PR!

# Description:

This code is a configuration file for a GitHub Actions workflow. GitHub Actions is a powerful automation tool provided by GitHub that allows you to define custom workflows for your repositories.

Let's break down what this specific workflow does:

1. **Trigger**: The workflow is triggered on a push event to the `main` branch. This means whenever there is a new commit pushed to the `main` branch, this workflow will be automatically executed.

2. **Jobs**: The workflow defines a single job named `publish`. Jobs are the building blocks of GitHub Actions workflows. Each job can contain one or more steps that perform specific tasks.

3. **Runs-on**: The `publish` job specifies that it will run on an Ubuntu environment (`ubuntu-latest`).

4. **Steps**:
   - `Checkout`: This step uses the `actions/checkout` action to pull the latest code from the repository, enabling subsequent steps to access the code.

   - `Set up QEMU`: This step uses the `docker/setup-qemu-action` action to set up QEMU for cross-platform builds.

   - `Set up Docker Buildx`: This step uses the `docker/setup-buildx-action` action to set up Docker Buildx, which is a Docker CLI plugin for building multi-platform images.

   - `Login Docker Hub`: This step uses the `docker/login-action` action to log in to Docker Hub using the provided Docker Hub username and access token (which are stored as secrets in the repository settings). This allows the workflow to push the Docker image to Docker Hub later.

   - `Build and publish`: This is the main step of the workflow. It uses the `docker/build-push-action` action to build the Docker image based on the `Dockerfile` in the repository root. The image is built for two platforms: `linux/amd64` and `linux/arm64`. After building the image, it is published to Docker Hub with the tag `mirotalk/sfu:latest`.

The final outcome of this workflow is that whenever there is a new push to the `main` branch, the Docker image defined in the `Dockerfile` will be built and published to Docker Hub, making it available for use by others.

Note: The success of this workflow is also dependent on the correct setup of Docker Hub credentials as secrets in the GitHub repository settings. Make sure to set the `DOCKERHUB_USERNAME` and `DOCKERHUB_ACCESS_TOKEN` secrets correctly.

**Comment by miroslavpejic85** [comment]
@rogerdz, just a question, have you maybe got to try the `linux/arm64`?

**Comment by rogerdz** [comment]
Hi @miỉoslavpejic85,
I can't try the arm version at the moment, you can test it on mac m1 or aws ec2 graviton 😬

Slow build due to arm emulation on amd, last time i tested it it would take about 1 hour to finish build.

**Comment by miroslavpejic85** [comment]
Hey @rogerdz,
This is only the first time or it always takes about 1h. If yes, it's not good :( and having not even tested the linux/arm64, I don't know if it is appropriate to keep this PR? what do you say?

**Comment by rogerdz** [comment]
You can test in AWS Graviton, it now free trial https://aws.amazon.com/vi/ec2/instance-types/t4/

It build away take 1h, it can improve using cache on github action but i haven't tried yet, we need cache npm package https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#

**Pull request merged**
